# Prometheus configuration for Node.js Jenkins CI/CD Pipeline
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    cluster: 'nodejs-jenkins-cicd'
    environment: 'staging'

# Rule files to be loaded
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  # Node.js application
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 10s
    metrics_path: /metrics

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 15s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # SonarQube
  - job_name: 'sonarqube'
    static_configs:
      - targets: ['sonarqube:9000']
    scrape_interval: 60s
    metrics_path: /api/monitoring/metrics
